# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Comingsoon Gohugo Theme"
license = "GPL3"
licenselink = "https://github.com/andresmazzo/gohugo-theme-comingsoon/blob/master/LICENSE"
description = "A base theme for coming soon webpages"
homepage = "https://github.com/andresmazzo/gohugo-theme-comingsoon"
tags = ["cominsoon"]
features = ["singlepage"]
min_version = "0.1.0"

[author]
  name = "Andres Mazzo"
  homepage = "https://andresmazzo.com"
