title = "My New Cool Project"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "gohugo-theme-comingsoon"
themesDir = "../../.."

[params]
  template = "simple"
  launch_date = "2021-01-01T00:00:00Z"